name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache disabled to avoid lockfile cache errors

      - name: Install dependencies
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci --no-audit --no-fund --include=dev
          else
            echo "No lockfile found, falling back to npm install"
            npm i --no-audit --no-fund
          fi

      - name: Debug Node & paths
        run: |
          node -v
          npm -v
          npx -v || true
          ls -la
          ls -la node_modules/.bin || true

      - name: Build site
        env:
          SITE_URL: https://herongdev.github.io/blog
          BASE: /blog/
          # Optional analytics (set in repo secrets and reference here)
          UMAMI_SRC: ${{ secrets.UMAMI_SRC }}
          UMAMI_WEBSITE_ID: ${{ secrets.UMAMI_WEBSITE_ID }}
          PLAUSIBLE_DOMAIN: ${{ secrets.PLAUSIBLE_DOMAIN }}
          GA_ID: ${{ secrets.GA_ID }}
          BAIDU_TONGJI_ID: ${{ secrets.BAIDU_TONGJI_ID }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
